### ISSUE TITLE
Layers licensing or merge into iced_aw?

### ISSUE THREAD

**Issue by genusistimelord** [ChrisPritchard/iced-experiments#1]
What sort of licensing might you be going to use for layers Or do you want to get this merged into iced_aw?

**Comment by ChrisPritchard** [comment]
I suppose I could propose it for iced_aw, but I want to battle test it in a real project first. For now, I'll just slap MIT on the repo

**Comment by genusistimelord** [comment]
ok thank you. I am in charge of Iced_aw so feel free to battle test it there too. no worries since its not like we dont have some weird conky controls already.
